In [39]:
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", None)

In [40]:
df = pd.read_parquet("../data/raw/electricity_raw.parquet", engine="fastparquet")

# Verify load
df.head()

,timestamp,curtailment,curtailment_energy,curtailment_solar_utility,curtailment_solar_utility_energy,curtailment_wind,curtailment_wind_energy,demand,demand_energy,demand_gross,demand_gross_energy,flow_exports,flow_exports_energy,flow_imports,flow_imports_energy,generation_renewable,generation_renewable_energy,generation_renewable_with_storage,generation_renewable_with_storage_energy,price,renewable_proportion,renewable_with_storage_proportion,emissions,energy,market_value,power,storage_battery
0,2000-01-01 00:00:00+10:00,0.0,0.0,0.0,0.0,0.0,0.0,6920.580,NaN,6920.580,NaN,NaN,NaN,NaN,NaN,162.083333,0.1623,162.083333,0.1623,20.180,14.05,14.05,6200.4981,6911.5833,139546.6626,6904.166667,NaN
1,2000-01-01 01:00:00+10:00,0.0,0.0,0.0,0.0,0.0,0.0,6847.860,NaN,6847.860,NaN,NaN,NaN,NaN,NaN,163.500000,0.1637,163.500000,0.1637,17.240,14.33,14.33,5615.3196,6293.2088,109020.1868,6241.166667,NaN
2,2000-01-01 02:00:00+10:00,0.0,0.0,0.0,0.0,0.0,0.0,6188.450,NaN,6188.450,NaN,NaN,NaN,NaN,NaN,162.833333,0.1629,162.833333,0.1629,14.180,15.79,15.79,4804.7439,5401.3333,76571.5262,5374.916667,NaN
3,2000-01-01 03:00:00+10:00,0.0,0.0,0.0,0.0,0.0,0.0,5469.910,NaN,5469.910,NaN,NaN,NaN,NaN,NaN,113.583333,0.1162,113.583333,0.1162,14.225,12.46,12.46,4020.3997,4491.4584,63901.7836,4460.333333,NaN
4,2000-01-01 04:00:00+10:00,0.0,0.0,0.0,0.0,0.0,0.0,4948.025,NaN,4948.025,NaN,NaN,NaN,NaN,NaN,103.166667,0.1031,103.166667,0.1031,8.150,12.51,12.51,3700.2430,4142.1667,33845.7011,4135.583333,NaN

In [41]:
# --- Dataset Overview ---------------------------------------------
rows, cols = (df.shape)
print(f"Rows: {rows}")
print(f"Columns: {cols}")

Rows: 226992
Columns: 27

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 226992 entries, 0 to 226991
Data columns (total 27 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   timestamp                                 226992 non-null  datetime64[us, UTC+10:00]
 1   curtailment                               226992 non-null  float64
 2   curtailment_energy                        226992 non-null  float64
 3   curtailment_solar_utility                 226992 non-null  float64
 4   curtailment_solar_utility_energy          226992 non-null  float64
 5   curtailment_wind                          226992 non-null  float64
 6   curtailment_wind_energy                   226992 non-null  float64
 7   demand                                    226982 non-null  float64
 8   demand_energy                             182370 non-null  float64
 9   demand_gross                              216807 non-null  float64
 10  demand_gross_energy                       172188 non-null  float64
 11  flow_exports                              146313 non-null  float64
 12  flow_exports_energy                       146313 non-null  float64
 13  flow_imports                              146313 non-null  float64
 14  flow_imports_energy                       146313 non-null  float64
 15  generation_renewable                      226551 non-null  float64
 16  generation_renewable_energy               226551 non-null  float64
 17  generation_renewable_with_storage         226551 non-null  float64
 18  generation_renewable_with_storage_energy  226551 non-null  float64
 19  price                                     226992 non-null  float64
 20  renewable_proportion                      216807 non-null  float64
 21  renewable_with_storage_proportion         216807 non-null  float64
 22  emissions                                 226983 non-null  float64
 23  energy                                    226983 non-null  float64
 24  market_value                              226983 non-null  float64
 25  power                                     226983 non-null  float64
 26  storage_battery                           8957 non-null    float64
dtypes: datetime64[us, UTC+10:00](1), float64(26)
memory usage: 46.8 MB

In [43]:
# --- Descriptive Stats ---------------------------------------------
df.describe()

,curtailment,curtailment_energy,curtailment_solar_utility,curtailment_solar_utility_energy,curtailment_wind,curtailment_wind_energy,demand,demand_energy,demand_gross,demand_gross_energy,flow_exports,flow_exports_energy,flow_imports,flow_imports_energy,generation_renewable,generation_renewable_energy,generation_renewable_with_storage,generation_renewable_with_storage_energy,price,renewable_proportion,renewable_with_storage_proportion,emissions,energy,market_value,power,storage_battery
count,226992.000000,226992.000000,226992.000000,226992.000000,226992.000000,226992.000000,226982.000000,182370.000000,216807.000000,172188.000000,146313.000000,146313.000000,146313.000000,146313.000000,226551.000000,226551.000000,226551.000000,226551.000000,226992.000000,216807.000000,216807.000000,226983.000000,226983.000000,2.269830e+05,226983.000000,8957.000000
mean,23.963874,23.963877,21.038683,21.038683,2.925191,2.925194,8137.762074,8135.553355,8475.637448,8559.249434,113.962222,113.961768,864.990903,864.983050,932.629431,909.101225,1032.287540,1007.416721,62.484340,14.828615,16.833444,6183.203032,7870.784673,5.264128e+05,7870.561391,121.160251
std,139.452475,139.431057,124.579268,124.564043,25.038043,25.016364,1394.409574,1419.532417,1393.094858,1409.158101,180.582202,180.581862,461.748200,461.743996,1386.612169,1392.373685,1425.224406,1432.915954,211.899040,18.831781,20.019375,1490.145003,1557.562286,2.232285e+06,1554.827440,77.126910
min,-65.397000,-65.397600,-65.397000,-65.397600,-25.700983,-27.627000,2577.155833,600.271700,4650.365000,1241.142500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-328.295833,0.000000,0.000000,1240.989800,3202.845500,-3.499110e+06,3202.845942,3.994178
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7103.471250,7078.705575,7458.793534,7515.472850,0.000000,0.000000,532.333333,532.333333,148.321025,123.592550,212.959596,186.089400,25.000000,2.690000,3.820000,5127.947650,6741.769350,1.896344e+05,6745.670879,67.553293
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8082.988750,8052.798050,8462.640000,8520.405050,6.827539,6.827539,839.865742,839.858423,458.939625,428.367500,563.558400,532.076100,39.185000,7.820000,9.400000,6215.749000,7892.034800,3.087672e+05,7894.595633,101.614748
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9087.985625,9106.565975,9371.295667,9467.618475,180.333333,180.333333,1158.928899,1158.916667,1048.684613,1005.941900,1182.421354,1147.236850,66.484722,19.005000,21.390000,7300.236050,8953.842600,5.287258e+05,8951.573020,162.613901
max,3503.327600,3474.199700,3318.139467,3279.008000,1314.630875,1319.542000,14524.884167,14530.037100,16134.240858,16151.025100,1546.858323,1546.858323,2848.250000,2848.250000,10898.422467,10895.759200,11477.422475,11474.729900,16157.503333,231.900000,233.080000,10798.487600,16457.483800,1.672426e+08,16412.192367,441.555112

In [44]:
print("Missing values for each column")
print(df.isna().sum())

Missing values for each column
timestamp                                        0
curtailment                                      0
curtailment_energy                               0
curtailment_solar_utility                        0
curtailment_solar_utility_energy                 0
curtailment_wind                                 0
curtailment_wind_energy                          0
demand                                          10
demand_energy                                44622
demand_gross                                 10185
demand_gross_energy                          54804
flow_exports                                 80679
flow_exports_energy                          80679
flow_imports                                 80679
flow_imports_energy                          80679
generation_renewable                           441
generation_renewable_energy                    441
generation_renewable_with_storage              441
generation_renewable_with_storage_energy       441
price                                            0
renewable_proportion                         10185
renewable_with_storage_proportion            10185
emissions                                        9
energy                                           9
market_value                                     9
power                                            9
storage_battery                             218035
dtype: int64

In [45]:
# Duplicated rows / timestamps
print(f"Duplicated rows: {df.duplicated().sum()}")
print(f"Duplicated timestamp: {df["timestamp"].duplicated().sum()}")

Duplicated rows: 0
Duplicated timestamp: 0

In [46]:
# --- Numerical Distributions ---------------------------------------------

numeric_columns = df.select_dtypes(
    include=np.number
).columns

for column in numeric_columns:
    fig = px.histogram(
        df,
        x=column,
        nbins=30,
        title=f"Distribution of {column}",
        labels={column: column},
        width=800,
        height=400
    )

    fig.update_layout(
        xaxis_title=column,
        yaxis_title="Frequency"
    )

    fig.write_html(f"../figures/histograms/{column}_distribution.html")

In [ ]:
# --- Outlier Detection ---------------------------------------------

for column in numeric_columns:
    fig = px.box(
        df,
        x=column,
        title=f"Boxplot of {column}"
    )

    fig.write_html(f"../figures/boxplots/{column}_boxplot.html")